function plotMidlines(protein,time)

dlNuc = protein{1};
dlCactNuc = protein{3};

DNmid = [dlNuc.NC10(1,:)  dlNuc.NC11(1,:)  ...
    dlNuc.NC12(1,:)  dlNuc.NC13(1,:) dlNuc.NC14(1,:)];
totalDlMid = [dlNuc.NC10(1,:)+dlCactNuc.NC10(1,:) ...
    dlNuc.NC11(1,:)+dlCactNuc.NC11(1,:) ...
    dlNuc.NC12(1,:)+dlCactNuc.NC12(1,:) ...
    dlNuc.NC13(1,:)+dlCactNuc.NC13(1,:) ...
    dlNuc.NC14(1,:)+dlCactNuc.NC14(1,:)];
totalDlBasal = [dlNuc.NC10(end,:)+dlCactNuc.NC10(end,:) ...
    dlNuc.NC11(end,:)+dlCactNuc.NC11(end,:) ...
    dlNuc.NC12(end,:)+dlCactNuc.NC12(end,:) ...
    dlNuc.NC13(end,:)+dlCactNuc.NC13(end,:) ...
    dlNuc.NC14(end,:)+dlCactNuc.NC14(end,:)];
nucDlBasal = [dlNuc.NC10(end,:) ...
    dlNuc.NC11(end,:) ...
    dlNuc.NC12(end,:) ...
    dlNuc.NC13(end,:) ...
    dlNuc.NC14(end,:)];
Tmid = [time.T10(:,1);time.T11(:,1);time.T12(:,1);time.T13(:,1);time.T14(:,1)];

figure
hold on
plot(Tmid,totalDlMid,'b')
plot(Tmid,DNmid,'r')
plot(Tmid,totalDlBasal,'--b')
plot(Tmid,nucDlBasal,'--r')
title('Amplitude & Basal Levels')
legend('Amplitude Total dl','Amplitude Nuclear dl','Basal Total dl','Basal Nuclear dl','location','Northwest')



end